### PR TITLE
Added IsAutoCloseEnabled bindable property for MoveToActionCell

### PR DESCRIPTION
**Pull request by alexmartinezm**
Hello,

I have created a new BindableProperty in MoveToActionCell called IsAutoCloseEnabledProperty. The main goal of this property is self-explanatory. I have also added a new SamplePage to interact with this new property.

[Demo](https://streamable.com/s/go4p2/zcbxdv)

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
Hi
Probably, it would be better to set True by default?

**Comment by alexmartinezm** [comment]
Ok. Furthermore, we could create a property called IsDestructive to achieve the MoveToAction sample behaviour (next goal).

Cheers,

**Comment by AndreiMisiukevich** [comment]
@alexmartinezm i will check it on weekend and merge
Thanks

**Comment by alexmartinezm** [comment]
I added a minor change to execute ForceClose before event and command. I have added this to avoid UI changes (eg converters in the sample) after swiping the cell.

**Comment by AndreiMisiukevich** [comment]
I am going to validate PR in 1h :)

**Pull request merged**
