### PR TITLE
Added OuterLeftContent and OuterRightContent

### PR DESCRIPTION
**Pull request by Zure1**
OuterLeftContent and OuterRightContent can be set for BaseActionViewCell now. Also added an example in the sample.

### CODE REVIEW

**Comment by Zure1** [comment]
Android implementation didn't work due to some width calculations being wrong and some changes in this PR broke the MoveToActionCell. All of this was fixed within the last four commits.

**Comment by Zure1** [comment]
Any update on the PR?

**Comment by AndreiMisiukevich** [comment]
@Zure1 i will merge it, if you need this changes asap :)
But as i told, i am going to refuse viewcells. So these changes won't make a lot of sense.

**Comment by Zure1** [comment]
I agree that once you've made the changes to the control not being a ViewCell, these changes will be obsolete and can be removed. For now, I need this changes in my project. Alternatively I can keep working on my fork and use it for my project, but then I wouldn't be able to make other PRs for your project I guess?

Once this PR is merged, I will try to implement left-to-right swipes.

**Comment by AndreiMisiukevich** [comment]
@Zure1 hm, i think you can go ahead with your fork
I am going to refactor it soon

**Comment by AndreiMisiukevich** [comment]
or i can merge to master for now
but it will be removed once i finish with "cell refusing" you know

**Comment by Zure1** [comment]
Do you have an approximate time of when this will happen?

**Comment by AndreiMisiukevich** [comment]
@Zure1 going to do it on Sunday or on the next week

**Pull request closed without merging**
